cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.Detalle.as_view(), name="cart_detail"),
    url(r'^add/(?P<producto_id>\d+)/$', views.Agregar.as_view(), name="cart_add"),
    url(r'^remove/(?P<producto_id>\d+)/$', views.Remove.as_view(), name="cart_remove")
]

soporte/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from tienda import urls as tiendaUrls
from cart import urls as cartUrls
from accounts import urls as accUrls
from django.conf import settings
from orders import urls as orderUrls
from paypal.standard.ipn import urls as paypalUrls
from payment import urls as paymentUrls
from main import urls as UrlsMain
#for socialauth
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

SOCIAL_AUTH_URL_NAMESPACE = 'social'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(UrlsMain,namespace="home")),
    url(r'^tienda/', include(tiendaUrls, namespace="tienda")),
    url(r'^cart/', include(cartUrls, namespace="cart")),
    url(r'^accounts/', include(accUrls,namespace="accounts")),
    url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs ={'document_root':settings.MEDIA_ROOT}
        ),

url(r'^orders/', include(orderUrls, namespace="orders")),
    url(r'^paypal/', include(paypalUrls)),
    url(r'^payment/', include(paymentUrls,namespace='payment')),

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    # Logout URL
    url(
        r'^users/logout/$',
        logout,
        {'next_page': '/products'},
        name="user-logout"),
]

tienda/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.Lista.as_view(), name="tienda"),
    url(r'^(?P<producto_id>\d+)/$', views.Detalle.as_view(), name="detalle"),
]

tienda/models.py
from django.db import models

class Producto(models.Model):
    imagen = models.FileField(upload_to='tienda/%Y/%m/%d/', null=True, blank=True)
    nombre = models.CharField(max_length=140)
    precio = models.FloatField()

tienda/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from .models import Producto
from cart.forms import CartAddProductForm

class Lista(View):
    def get(self, request):
        productos = Producto.objects.all()
        template_name = 'tienda/lista.html'
        context = {
        'productos':productos
        }
        return render(request, template_name, context)

class Detalle(View):
    def get(self, request, producto_id):
        template_name = 'tienda/detalle.html'
        producto = get_object_or_404(Producto,id=producto_id)
        form = CartAddProductForm()
        context = {
        'producto':producto,
        'form':form
        }
        return render(request, template_name, context)

tienda/templates/tienda/detalle.html
{% extends 'base.html'%}
{%block titulo%}
{{producto.nombre}}
{%endblock titulo%}
{% block content%}
<div id="wrapper">
	<br></br>
	<div class="product-images"><a><img src="/media/{{producto.imagen}}" height="175"></a></div>
	<h5>{{producto.nombre}}</h5>
	<h4> $ {{producto.precio}}</h4>
	<form action="{%url 'cart:cart_add' producto.id%}" method="post">
		{%csrf_token%}{{form.as_p}}
		<input type="submit" value="Agregar al Carrito" class="waves-effect waves-light btn  light-blue"></input>
	</form>
</div>
{% endblock content%}

tienda/templates/tienda/lista.html
{% extends 'base.html'%}{%block titulo%}Tienda{%endblock titulo%} {% block content%}

<div id="wrapper">
	<br></br>
	<h1 class="center">Articulos en venta</h1> {%for producto in productos%}
	<div class="tabla"  align="center">
		<a href="{%url 'tienda:detalle' producto.id%}">
			<h2><img src="/media/{{producto.imagen}}" height="150" width="205"></h2>
			<h4> $ {{producto.precio}}</h4>
			<h5>{{producto.nombre}}</h5>
		</a>
		<form action="{%url 'tienda:detalle' producto.id%}">
			{%csrf_token%} {{form.as_p}}
			<input type="submit" value="Detalle Producto" class="waves-effect waves-light btn  light-blue"></input>
		</form>
	</div>
	{%empty%}
	<h2>No hay productos para mostrar</h2> {%endfor%}
</div>
{% endblock content%}