cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.Detalle.as_view(), name="cart_detail"),
    url(r'^add/(?P<producto_id>\d+)/$', views.Agregar.as_view(), name="cart_add"),
    url(r'^remove/(?P<producto_id>\d+)/$', views.Remove.as_view(), name="cart_remove")
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^create/$',views.CreateOrder.as_view(), name="create"),
]	

soporte/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from tienda import urls as tiendaUrls
from cart import urls as cartUrls
from accounts import urls as accUrls
from django.conf import settings
from orders import urls as orderUrls
from paypal.standard.ipn import urls as paypalUrls
from payment import urls as paymentUrls
from main import urls as UrlsMain
#for socialauth
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

SOCIAL_AUTH_URL_NAMESPACE = 'social'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(UrlsMain,namespace="home")),
    url(r'^tienda/', include(tiendaUrls, namespace="tienda")),
    url(r'^cart/', include(cartUrls, namespace="cart")),
    url(r'^accounts/', include(accUrls,namespace="accounts")),
    url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs ={'document_root':settings.MEDIA_ROOT}
        ),

url(r'^orders/', include(orderUrls, namespace="orders")),
    url(r'^paypal/', include(paypalUrls)),
    url(r'^payment/', include(paymentUrls,namespace='payment')),

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    # Logout URL
    url(
        r'^users/logout/$',
        logout,
        {'next_page': '/products'},
        name="user-logout"),
]

tienda/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.Lista.as_view(), name="tienda"),
    url(r'^(?P<producto_id>\d+)/$', views.Detalle.as_view(), name="detalle"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

CHOICES = ((i,str(i)) for i in range(1,21))

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=CHOICES, coerce=int)
	update = forms.BooleanField(required=False,initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CartAddProductForm
from django.views.generic import View
from .cart import Cart
from tienda.models import Producto

class Agregar(View):
	def post(self,request,producto_id):
		cart = Cart(request)
		producto = get_object_or_404(Producto,id=producto_id)
		form = CartAddProductForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			cart.add(producto=producto,
				quantity=cd['quantity'],
				update_quantity=cd['update'])
		return redirect('tienda:tienda')

class Remove(View):
	def get(self,request,producto_id):
		cart = Cart(request)
		producto = get_object_or_404(Producto,id=producto_id)
		cart.remove(producto)
		return redirect('cart:cart_detail')

class Detalle(View):
	def get(self,request):
		cart = Cart(request)
		return render(request,'cart/detalle.html',{'cart':cart})

cart/templates/cart/detalle.html
{% extends 'base.html'%} {% block content%}
<html>

<head>
    <meta charset="utf-8">
    <title>Carrito</title>
    <meta charset="utf-8">
</head>

<body>
    <div id="wrapper" , class="center">
        <br></br>
        <h1 class="center">Tu carrito</h1>
        <table>
            <thead>
                <tr>
                    <th>|  Imagen  |</th>
                    <th>|  Producto  |</th>
                    <th>|  Cantidad  |</th>
                    <th>|  Quitar  |</th>
                    <th>|  Precio Unitario  |</th>
                    <th>|  SubTotal  |</th>
                </tr>
            </thead>
            <tbody>
                {%for item in cart%} {%with producto=item.producto%}
                <tr>
                    <td>
                        <img src="/media/{{producto.imagen}}" height="100">
                    </td>
                    <td>
                        {{producto.nombre}}
                    </td>
                    <td>
                        {{item.quantity}}
                    </td>
                    <td>
                        <a href="{%url 'cart:cart_remove' producto.id%}">Quitar</a>
                    </td>
                    <td>
                        $ {{item.precio}}
                    </td>
                    <td>
                        $ {{item.precio_total}}
                    </td>
                </tr>
                {%endwith%} {%endfor%}
                <tr>
                    <td>Total</td>
                    <td colspan="4"></td>
                    <td>$ {{cart.get_precio_total}}</td>
                </tr>
            </tbody>
        </table>


        <button class="waves-effect waves-light btn  light-blue" >
            <a href="{%url 'tienda:tienda'%}" class="white-text">
            Continuar comprando
            </a>
        </button>


         <button class="waves-effect waves-light btn  light-blue" >
            <a href="{%url 'orders:create'%}" class="white-text">
            Pagar
            </a>
        </button>

    </div>
</body>

</html>
{% endblock content%}