accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, login,logout_then_login
from . import views

urlpatterns = [
	url(r'^registro/$', views.Registration.as_view(),name="registro"),
	url(r'^profile/$', views.Dashboard.as_view(), name="profile"),
	url(r'^detailprofile/$', views.DetailProfile.as_view(), name="detailprofile"),
	url(r'^login/$', login, name="login"),
	url(r'^logout/$', logout, name="logout"),
	url(r'^logout-then-login/$', logout_then_login, name="logout_then_login"),
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.Detalle.as_view(), name="cart_detail"),
    url(r'^add/(?P<producto_id>\d+)/$', views.Agregar.as_view(), name="cart_add"),
    url(r'^remove/(?P<producto_id>\d+)/$', views.Remove.as_view(), name="cart_remove")
]

soporte/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from tienda import urls as tiendaUrls
from cart import urls as cartUrls
from accounts import urls as accUrls
from django.conf import settings
from orders import urls as orderUrls
from paypal.standard.ipn import urls as paypalUrls
from payment import urls as paymentUrls
from main import urls as UrlsMain
#for socialauth
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

SOCIAL_AUTH_URL_NAMESPACE = 'social'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(UrlsMain,namespace="home")),
    url(r'^tienda/', include(tiendaUrls, namespace="tienda")),
    url(r'^cart/', include(cartUrls, namespace="cart")),
    url(r'^accounts/', include(accUrls,namespace="accounts")),
    url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs ={'document_root':settings.MEDIA_ROOT}
        ),

url(r'^orders/', include(orderUrls, namespace="orders")),
    url(r'^paypal/', include(paypalUrls)),
    url(r'^payment/', include(paymentUrls,namespace='payment')),

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    # Logout URL
    url(
        r'^users/logout/$',
        logout,
        {'next_page': '/products'},
        name="user-logout"),
]

tienda/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.Lista.as_view(), name="tienda"),
    url(r'^(?P<producto_id>\d+)/$', views.Detalle.as_view(), name="detalle"),
]

templates/base.html
<!DOCTYPE html>
{%load static%}

<html>

<head>
	<title>
		{%block titulo%} TotalServiceGeeks{%endblock titulo%}
	</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!--Import Google Icon Font-->
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
	<!--Import Google Icon Font-->
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
	
	{%block head%} {%endblock head%}
</head>

<body>



	<nav class="blue darken-4 navbar-fixed">
		<div class="nav-wrapper">
			<a href="{%url 'home:home'%}" class="brand-logo">TotalServiceGeeks</a>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
				<li><a href="{%url 'home:home'%}">Inicio</a></li>
				{%if request.user.is_authenticated%}
					<li><a href="#">Perfil</a></li>
					<li><a href="{% url 'accounts:registro'%}">Cerrar Sesión</a></li>
					<li><a href="{% url 'tienda:tienda'%}">Tienda</a></li>
					<li><a href="{% url 'cart:cart_detail'%}">
					{%with total_items=cart|length%}<img src="/media/tienda/carrito.png {{producto.imegen}}" height="20">
					{{total_items}} {%if total_items > 0%}
				 	{{total_items|pluralize}}
				  	{%else%} {{tota_items}} {%endif%}{%endwith%}</a></li>
				{%else%}
				<li><a href="#">Iniciar Sesión</a></li>
				<li><a href="{% url 'accounts:registro'%}">Registrate</a></li>
				{%endif%}
				
			</ul>
		</div>
	</nav>	
	{%if request.user.is_authenticated%}
	<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
		 <a class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>	
	</div>
	{%endif%}
	{%block content%}
	
	

	{%endblock content%}
     <!--Import jQuery before materialize.js-->
	 <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	 <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
	 {%block scripts%}
	 {%endblock scripts%}
</body>

</html>